from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import io
import datetime

def generate_mission_pdf(row):
    """
    Generates a 'Mission Order' PDF for a specific pincode row.
    Returns: BytesIO object (the PDF file in memory).
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # --- 1. Header (Cyber Style) ---
    c.setFillColorRGB(0.05, 0.07, 0.09) # Dark background
    c.rect(0, height - 100, width, 100, fill=1, stroke=0)
    
    c.setFillColor(colors.cyan)
    c.setFont("Courier-Bold", 24)
    c.drawString(50, height - 50, "PROJECT DRISHTI | MISSION ORDER")
    
    c.setFont("Courier", 12)
    c.drawString(50, height - 70, f"DATE: {datetime.date.today()} | REF: UIDAI-SEC-{row['pincode']}")

    # --- 2. Target Identification ---
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 150, f"TARGET PINCODE: {row['pincode']}")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 175, f"📍 Location: {row['district']}, {row['state']}")
    
    # Handle lat/lon safely
    lat = round(row['lat'], 4) if 'lat' in row else "Unknown"
    lon = round(row['lon'], 4) if 'lon' in row else "Unknown"
    c.drawString(50, height - 195, f"🛰️ GPS Coordinates: {lat}, {lon}")
    
    # --- 3. Threat Intelligence ---
    # Draw a Red Box for Risk
    c.setStrokeColor(colors.red)
    c.setLineWidth(2)
    c.rect(50, height - 320, 500, 100)
    
    c.setFillColor(colors.red)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(70, height - 245, "⚠️ THREAT ASSESSMENT: CRITICAL")
    
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 12)
    c.drawString(70, height - 270, f"Primary Anomaly: {str(row['primary_risk_factor']).upper().replace('_', ' ')}")
    c.drawString(70, height - 290, f"Velocity Index: {int(row['velocity_index'])} updates/period")
    c.drawString(70, height - 310, f"Ghost Ratio: {round(row['ghost_ratio'], 2)} (Demographic vs Biometric mismatch)")

    # --- 4. Field Instructions (The Action Plan) ---
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 360, "INSPECTOR CHECKLIST (MANDATORY)")
    
    c.setFont("Helvetica", 12)
    checklist = [
        "Inspect Operator Log Books for evidence of batch processing.",
        "Verify physical presence of documented residents (Random Sampling).",
        "Check Biometric Device (GPS Module) for tampering or spoofing.",
        "Cross-reference Demographic Update forms with supporting docs.",
        "Immediate suspension of operator ID if 'Ghost' pattern confirmed."
    ]
    
    y = height - 390
    for item in checklist:
        c.rect(50, y, 10, 10) # Checkbox
        c.drawString(70, y+2, item)
        y -= 25

    # --- 5. Footer ---
    c.setStrokeColor(colors.grey)
    c.line(50, 100, width-50, 100)
    c.setFont("Courier", 10)
    c.setFillColor(colors.grey)
    c.drawString(50, 80, "CONFIDENTIAL - FOR AUTHORIZED PERSONNEL ONLY")
    c.drawString(50, 65, "Generated by Project Drishti AI Engine | UIDAI Hackathon 2026")

    c.save()
    buffer.seek(0)
    return buffer