from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import io
import datetime

def generate_mission_pdf(row):
    """
    Generates a 'Mission Order' PDF for a specific pincode row.
    Returns: BytesIO object (the PDF file in memory).
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # --- 1. Header (Cyber Style) ---
    # Dark header background
    c.setFillColorRGB(0.05, 0.07, 0.09) 
    c.rect(0, height - 100, width, 100, fill=1, stroke=0)
    
    # Title
    c.setFillColor(colors.cyan)
    c.setFont("Courier-Bold", 24)
    c.drawString(50, height - 50, "PROJECT DRISHTI | MISSION ORDER")
    
    # Subheader / Meta info
    c.setFont("Courier", 12)
    c.setFillColor(colors.white)
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    c.drawString(50, height - 75, f"GENERATED: {timestamp} | REF: UIDAI-SEC-{row['pincode']}")

    # --- 2. Target Identification ---
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 150, f"TARGET PINCODE: {row['pincode']}")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 175, f"📍 Location: {row['district']}, {row['state']}")
    
    # Coordinates
    lat = round(float(row.get('lat', 0)), 4)
    lon = round(float(row.get('lon', 0)), 4)
    gps_status = "VERIFIED" if row.get('geo_accuracy') == 'High' else "APPROXIMATE"
    c.drawString(50, height - 195, f"🛰️ GPS Coordinates: {lat}, {lon} ({gps_status})")
    
    # --- 3. Threat Intelligence ---
    # Draw a Red Box for Risk
    c.setStrokeColor(colors.red)
    c.setLineWidth(2)
    c.rect(50, height - 330, 500, 110)
    
    c.setFillColor(colors.red)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(70, height - 250, "⚠️ THREAT ASSESSMENT: CRITICAL")
    
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 12)
    
    # Handle potentially missing or float values gracefully
    anomaly_type = str(row['primary_risk_factor']).upper().replace('_', ' ')
    velocity = int(row['velocity_index'])
    ghost_ratio = round(float(row.get('ghost_ratio', 0)), 2)
    adult_spike = round(float(row.get('adult_spike_ratio', 0)), 2)

    c.drawString(70, height - 275, f"Primary Anomaly: {anomaly_type}")
    c.drawString(70, height - 295, f"Velocity Index:  {velocity} updates/period")
    c.drawString(70, height - 315, f"Ghost Ratio:     {ghost_ratio} (Address vs Biometric mismatch)")
    c.drawString(70, height - 335, f"Adult Spike:     {adult_spike} (New Adult Enrolments)")

    # --- 4. Field Instructions (The Action Plan) ---
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 380, "INSPECTOR CHECKLIST (MANDATORY)")
    
    c.setFont("Helvetica", 12)
    checklist = [
        "Inspect Operator Log Books for evidence of batch processing.",
        "Verify physical presence of documented residents (Random Sampling).",
        "Check Biometric Device (GPS Module) for tampering or spoofing.",
        "Cross-reference Demographic Update forms with supporting docs.",
        "Immediate suspension of operator ID if 'Ghost' pattern confirmed.",
        "Upload site photos to SITAA mobile app."
    ]
    
    y = height - 410
    for item in checklist:
        c.rect(50, y, 10, 10) # Checkbox
        c.drawString(70, y+2, item)
        y -= 25

    # --- 5. Map Placeholder (Optional visual cue) ---
    c.setStrokeColor(colors.grey)
    c.setLineWidth(1)
    c.rect(50, y - 150, 200, 120)
    c.setFont("Courier", 10)
    c.setFillColor(colors.grey)
    c.drawString(90, y - 100, "[ MAP ATTACHMENT ]")
    c.drawString(75, y - 115, "Refer to Dashboard for Live View")

    # --- 6. Footer ---
    c.setStrokeColor(colors.grey)
    c.line(50, 50, width-50, 50)
    c.setFont("Courier", 10)
    c.setFillColor(colors.grey)
    c.drawString(50, 35, "CONFIDENTIAL - FOR AUTHORIZED PERSONNEL ONLY")
    c.drawString(50, 20, "Generated by Project Drishti AI Engine | UIDAI Hackathon 2026")

    c.save()
    buffer.seek(0)
    return buffer